Changes Sh.call (e.g. sh "args") to Sh.returnStdOut().
Because of exception, e.g.
RejectedAccessException: Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (com.cloudogu.ces.cesbuildlib.Git sh java.lang.String)