MavenDocker: Refactored, because calling super method not possible.
Calling createCommandLineArgs() in MavenInDocker resulted in:

org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (com.cloudogu.ces.cesbuildlib.MavenInDocker createCommandLineArgs java.lang.String)