Revert "Try Groovy Assert."
This reverts commit 7233886

org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: unclassified staticMethod groovy.test.GroovyAssert assertTrue java.lang.String java.lang.Boolean