Avoids required script approval for Maven deployment.
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (com.cloudogu.ces.cesbuildlib.Maven$DeployGoal createGoal com.cloudogu.ces.cesbuildlib.Maven$Nexus3 java.lang.String)