MavenInDocker: Remove TemplateEngine, because not allowed in Jenkins.
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use new groovy.text.SimpleTemplateEngine